# Generated by Django 3.1.3 on 2020-11-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrejunApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='filename',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
