# Generated by Django 3.1.3 on 2020-11-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrejunApp', '0002_candidate_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
